export class ButtonAcces {
    btnNuevo: boolean;
    btnEditar: boolean;
    btnEliminar: boolean;
    btnGrabar: boolean;
    btnCerrar: boolean;
    btnTransferir: boolean;
    btnArchivo: boolean;
    btnPDF: boolean;
    btnEXCEL: boolean;
    btnDownload: boolean;
    btnGuiar: boolean;
    btnVizualizar: boolean;
    btnAdicionarEliminar: boolean;
    btnMenuPadre: boolean;
    btnMenuHijo: boolean;
    btnBuscar: boolean;
    btnAnular: boolean;
    btnActivar: boolean;
    btnExportar: boolean;
    btnExpExcel: boolean;
    btnImpExcel: boolean;
    btnImpFile: boolean;
    btnAprobar: boolean;
    btnRevisar: boolean;
    btnAsignar: boolean;
    btnImprimir: boolean;
    btnEnviarSAP: boolean;
    btnRecharSAP: boolean;
    btnDuplicar: boolean;
    btnCopiarPedido: boolean;
    btnEnviarCorreo: boolean;
    btnFlujoAprobacion: boolean;
    btnResumen: boolean;
    btnAgregar: boolean;
    btnEnviar: boolean;

    constructor() {
        this.btnNuevo = true;
        this.btnEditar = true;
        this.btnEliminar = true;
        this.btnGrabar = true;
        this.btnCerrar = true;
        this.btnTransferir = true;
        this.btnArchivo = true;
        this.btnPDF = true;
        this.btnEXCEL = true;
        this.btnDownload = true;
        this.btnGuiar = true;
        this.btnVizualizar = true;
        this.btnAdicionarEliminar = true;
        this.btnMenuPadre = true;
        this.btnMenuHijo = true;
        this.btnBuscar = true;
        this.btnAnular = true;
        this.btnActivar = true;
        this.btnExpExcel = true;
        this.btnImpExcel = true;
        this.btnImpFile = true;
        this.btnAprobar = true;
        this.btnRevisar = true;
        this.btnAsignar = true;
        this.btnImprimir = true;
        this.btnEnviarSAP = true;
        this.btnRecharSAP = true;
        this.btnDuplicar = true;
        this.btnCopiarPedido = true;
        this.btnEnviarCorreo = true;
        this.btnFlujoAprobacion = true;
        this.btnResumen = true;
        this.btnAgregar = true;
        this.btnEnviar = true;
    }
}
